# Generated by Django 4.0 on 2021-12-14 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0005_alter_post_options_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
